version:  '3.9'

services:
   java_app:
        container_name: java_app
        image: pee-java-app:1.0.0
        build: .
        ports:
            - 8080:8080
        environment:
            - DATABASE_URL=jdbc:postgresql://localhost:5432/postgres
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=postgres
        depends_on:
            - java_db
   java_db:
        container_name: java_db
        image: postgres:12
        ports:
            - 5432:5432
        environment:
            - POSTGRES_URL= postgres
            - POSTGRES_USERNAME= postgres
            - POSTGRES_PASSWORD= postgres
   java_app_test:
        container_name: java_app_test
        image: pee-java-app:1.0.0
        build: .
        ports:
            - 8080:8080
        environment:
            - DATABASE_URL=jdbc:postgresql://host.docker.internal:5432/postgres
            - DATABASE_USERNAME=postgres
            - DATABASE_PASSWORD=postgres